version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./agendamento-palestra-back/.env
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./agendamento-palestra-back
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./agendamento-palestra-back/.env
    depends_on:
      - mariadb
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./agendamento-palestra-web
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '4200:80'

volumes:
  db_data:
