version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: agendamento_palestra
      MYSQL_USER: diogo
      MYSQL_PASSWORD: diogo123
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./agendamento-palestra-back
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: diogo
      DB_PASSWORD: diogo123
      DB_DATABASE: agendamento_palestra
    depends_on:
      - mariadb
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./agendamento-palestra-web
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '4200:80'

volumes:
  db_data:
