version: '3.7'

services:
  web:
    build:
      context: ./agendamento-palestra-web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - back

  back:
    build:
      context: ./agendamento-palestra-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_USER=agendamento_user
      - DATABASE_PASSWORD=agendamento_password
      - DATABASE_NAME=agendamento_palestras
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=agendamento_palestras
      - MYSQL_USER=agendamento_user
      - MYSQL_PASSWORD=agendamento_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
